import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
  welcomeCard: {
    marginTop: 60,
    width: "90%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "white",
    boxShadow: "0px 4px 10px rgba(0, 0, 0, 0.1)",
    textAlign: "center",
  },
  cardTitle: {
    fontFamily: "Montserrat",
    fontWeight: 800,
    fontSize: 20,
    color: "white",
  },
  cardTitleStyle: {
    boxShadow: "inset 0px -4px 4px rgba(0, 0, 0, 0.16)",
    borderRadius: "0px 0px 32px 32px",
    background: "#FCAC37",
    width: 280,
    height: 70,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  divText: {
    marginTop: 25,
    marginBottom: 25,
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    textAlign: "center",
    width: "80%",
  },
  text: {
    fontFamily: "Montserrat",
    fontWeight: 600,
    fontSize: 16,
    color: "rgba(0, 0, 0, 0.85)",
  },
  firstContainer: {
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    background: "#F2F2F2",
    borderRadius: 32,
    width: "90%",
  },
  cardCow: {
    boxShadow: "inset 0px -4px 4px rgba(0, 0, 0, 0.16)",
    borderRadius: "0px 0px 32px 32px",
    background: "#4F4F4F",
    width: 130,
    height: 40,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
  },
  cardTitleCow: {
    fontFamily: "Montserrat",
    fontWeight: 400,
    fontSize: 16,
    color: "white",
  },
  secondContainer: {
    marginTop: 40,
    marginBottom: 40,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    background: "#F2F2F2",
    borderRadius: 32,
    width: "90%",
  },
  divCard: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: "white",
    borderRadius: 32,
    width: 450,
    height: 458,
    marginTop: 50,
    marginBottom: 50,
  },
  textLevel: {
    fontFamily: "Montserrat",
    fontWeight: 800,
    fontSize: 24,
    color: "rgba(79, 79, 79, 1)",
  },
  textLevelInfo: {
    fontFamily: "Montserrat",
    fontWeight: 400,
    fontSize: 16,
    color: "rgba(79, 79, 79, 1)",
  },
  level: {
    marginTop: 5,
    fontFamily: "Montserrat",
    fontWeight: 800,
    fontSize: 24,
    color: "rgba(36, 41, 55, 1)",
  },
}));

export { useStyles };
